packages:
  # Include all of the core configuration
  core: !include esphome-project-esp8266-powerplug.yaml

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: patrickse.powerplug
    version: dev # This will be replaced by the github workflows with the `release` version
  friendly_name: Powerplug
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true    

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://patrickse/esphome_templates/esphome-project-esp8266-powerplug.yaml@main